// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nghweeihoucgoiyrpgfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5naHdlZWlob3VjZ29peXJwZ2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTM5MjEsImV4cCI6MjA2MDU2OTkyMX0.RZHIA_B11rg7eDRXz_iwKvDK4eKExksqamvXFk7t_QY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);